### ISSUE TITLE
Error: [Errno 2] No such file or directory: 'hcxpcaptool'

### ISSUE THREAD

**Issue by NastyaGrifon** [4k4xs4pH1r3/wifite3#11]
Capturing PMKID fails with an error `No such file or directory: 'hcxpcaptool'`

### hcxpcaptool was deprecated and should be replaced with hcxpcapngtool

Quick and dirty fix would be to create a symbolic link `sudo ln -s $(which hcxpcapngtool) /usr/local/bin/hcxpcaptool` 
[Like suggested here](https://askubuntu.com/questions/1308282/hcxpcap-tool-missing)

Proper fix would be to check whether command `hcxpcaptool` is available and if not check for `hcxpcapngtool`

Manjaro (testing branch)
hcxtools version 6.2.7-1
Latest wifite3 version ([5a0a455](https://github.com/4k4xs4pH1r3/wifite3/commit/5a0a4559ffce4272551d10d875ed100ca9214aa8))

![Screenshot from 2022-07-28 16-30-23](https://user-images.githubusercontent.com/14854919/181510869-d2c6ce57-fb0f-40bd-acf5-653f2a6bedbc.jpg)

Airgeddon [had simillar issue](https://github.com/v1s1t0r1sh3r3/airgeddon/issues/407), but is working fine

**Comment by 4k4xs4pH1r3** [comment]
Thank you @NastyaGrifon added to the script to automate this ;)
